
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum ActionPointType
    {
        None = 0,
        PreCauseDamage = 1,
        PreReceiveDamage = 2,
        PostCauseDamage = 3,
        PostReceiveDamage = 4,
        PostGiveCure = 5,
        PostReceiveCure = 6,
        AssignEffect = 7,
        ReceiveEffect = 8,
        PostGiveBuff = 9,
        PostReceiveBuff = 10,
        PreSpell = 11,
        PostSpell = 12,
        PrePlayBattle = 21,
        PostPlayBattle = 22,
    }

} 

