
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.Battle
{ 
    /// <summary>
    /// 战斗效果触发类型
    /// </summary>
    public enum EffectTriggerType
    {
        /// <summary>
        /// 效果被创建时立即触发
        /// </summary>
        Create = 0,
        /// <summary>
        /// 技能施法触发的
        /// </summary>
        Spell = 1,
        /// <summary>
        /// 行动相关事件触发
        /// </summary>
        ActionEvent = 2,
    }

} 

