
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.Battle
{ 
    public enum TargetType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 敌人
        /// </summary>
        Enemy = 1,
        /// <summary>
        /// 友方
        /// </summary>
        Friend = 2,
        /// <summary>
        /// 友方除自己
        /// </summary>
        FriendWithoutSelf = 3,
        /// <summary>
        /// 位置
        /// </summary>
        Posion = 4,
        /// <summary>
        /// 全体
        /// </summary>
        All = 5,
        /// <summary>
        /// 自己（施法者）
        /// </summary>
        Self = 6,
        /// <summary>
        /// 有效果选择
        /// </summary>
        EffectSelect = 7,
    }

} 

