
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Battle
{
public sealed partial class EffectTriggerDesc : Luban.BeanBase
{
    public EffectTriggerDesc(ByteBuf _buf) 
    {
        Type = (Battle.EffectTriggerType)_buf.ReadInt();
        Param1 = _buf.ReadInt();
        Param2 = _buf.ReadInt();
    }

    public static EffectTriggerDesc DeserializeEffectTriggerDesc(ByteBuf _buf)
    {
        return new Battle.EffectTriggerDesc(_buf);
    }

    /// <summary>
    /// 类型
    /// </summary>
    public readonly Battle.EffectTriggerType Type;
    /// <summary>
    /// 参数1
    /// </summary>
    public readonly int Param1;
    /// <summary>
    /// 参数2
    /// </summary>
    public readonly int Param2;
   
    public const int __ID__ = 1771683426;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "type:" + Type + ","
        + "param1:" + Param1 + ","
        + "param2:" + Param2 + ","
        + "}";
    }
}

}
