
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.Battle
{ 
    public enum EffectType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 伤害dmg
        /// </summary>
        Damage = 1,
        /// <summary>
        /// 治疗
        /// </summary>
        Cure = 2,
        /// <summary>
        /// 添加buff
        /// </summary>
        AddBuff = 3,
        /// <summary>
        /// 添加状态
        /// </summary>
        AddStatus = 4,
        /// <summary>
        /// 修改卡牌附加属性，回合结束移除
        /// </summary>
        ModifyCardProp = 5,
    }

} 

