
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.Battle
{ 
    public enum CastPosType
    {
        /// <summary>
        /// 目标位置（跟随）
        /// </summary>
        TargetPos = 0,
        /// <summary>
        /// 施法时目标位置
        /// </summary>
        TargetPosCast = 1,
        /// <summary>
        /// 方向
        /// </summary>
        Direction = 2,
    }

} 

