
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.Battle
{ 
    /// <summary>
    /// 目标选择类型
    /// </summary>
    public enum TargetSelectType
    {
        /// <summary>
        /// 默认攻击目标或者触发目标
        /// </summary>
        None = 0,
        /// <summary>
        /// 全体
        /// </summary>
        All = 1,
        /// <summary>
        /// 敌方
        /// </summary>
        Enemy = 2,
        /// <summary>
        /// 友方
        /// </summary>
        Friend = 3,
        /// <summary>
        /// 自己
        /// </summary>
        Self = 4,
    }

} 

