
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.Battle
{ 
    public enum AreaType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 目标P2P
        /// </summary>
        P2P = 1,
        /// <summary>
        /// 圆形
        /// </summary>
        Circular = 2,
        /// <summary>
        /// 矩形
        /// </summary>
        Rect = 3,
        /// <summary>
        /// 扇形
        /// </summary>
        Sector = 4,
        /// <summary>
        /// 目标阵营全体
        /// </summary>
        TargetAllSide = 5,
    }

} 

