
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Battle
{
public sealed partial class Effect : Luban.BeanBase
{
    public Effect(ByteBuf _buf) 
    {
        EffectType = (Battle.EffectType)_buf.ReadInt();
        Param1 = _buf.ReadInt();
        Param2 = _buf.ReadInt();
        Param3 = _buf.ReadInt();
        Param4 = _buf.ReadInt();
        Param5 = _buf.ReadInt();
        Param6 = _buf.ReadInt();
    }

    public static Effect DeserializeEffect(ByteBuf _buf)
    {
        return new Battle.Effect(_buf);
    }

    public readonly Battle.EffectType EffectType;
    public readonly int Param1;
    public readonly int Param2;
    public readonly int Param3;
    public readonly int Param4;
    public readonly int Param5;
    public readonly int Param6;
   
    public const int __ID__ = 379546503;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "effectType:" + EffectType + ","
        + "param1:" + Param1 + ","
        + "param2:" + Param2 + ","
        + "param3:" + Param3 + ","
        + "param4:" + Param4 + ","
        + "param5:" + Param5 + ","
        + "param6:" + Param6 + ","
        + "}";
    }
}

}
