
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class BuffDesc : Luban.BeanBase
{
    public BuffDesc(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        IsGlobal = _buf.ReadBool();
        Duration = _buf.ReadInt();
        DecreaseLayer = _buf.ReadInt();
        MaxLayer = _buf.ReadInt();
        MaxTriggerTimes = _buf.ReadInt();
        RefreshMode = (GameLogic.Battle.EBuffRefreshMode)_buf.ReadInt();
        TriggerMode = (GameLogic.Battle.EBuffTriggerMethod)_buf.ReadInt();
        TriggerInterval = _buf.ReadInt();
        RemoveMode = (GameLogic.Battle.EBuffRemoveMethod)_buf.ReadInt();
        RemoveEvent = _buf.ReadString();
        TreeName = _buf.ReadString();
    }

    public static BuffDesc DeserializeBuffDesc(ByteBuf _buf)
    {
        return new BuffDesc(_buf);
    }

    /// <summary>
    /// 技能id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 说明
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 全局buff不会移除
    /// </summary>
    public readonly bool IsGlobal;
    /// <summary>
    /// 持续时间ms；<br/>填-1表示永久持续
    /// </summary>
    public readonly int Duration;
    /// <summary>
    /// 超时减少的层数：<br/>不填表示减少所有层
    /// </summary>
    public readonly int DecreaseLayer;
    /// <summary>
    /// 最大层数<br/>不填表示没有层数限制
    /// </summary>
    public readonly int MaxLayer;
    /// <summary>
    /// 最多生效次数：<br/>不填表示没有次数限制
    /// </summary>
    public readonly int MaxTriggerTimes;
    /// <summary>
    /// buff刷新模式：<br/>可以用竖线联合多种方式，如：IncreaseStack|RefreshDuration
    /// </summary>
    public readonly GameLogic.Battle.EBuffRefreshMode RefreshMode;
    /// <summary>
    /// buff触发模式可以用竖线联合多种方式
    /// </summary>
    public readonly GameLogic.Battle.EBuffTriggerMethod TriggerMode;
    /// <summary>
    /// 触发间隔ms
    /// </summary>
    public readonly int TriggerInterval;
    /// <summary>
    /// buff移除模式
    /// </summary>
    public readonly GameLogic.Battle.EBuffRemoveMethod RemoveMode;
    public readonly string RemoveEvent;
    /// <summary>
    /// buff图
    /// </summary>
    public readonly string TreeName;
   
    public const int __ID__ = -1458387548;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "isGlobal:" + IsGlobal + ","
        + "duration:" + Duration + ","
        + "decreaseLayer:" + DecreaseLayer + ","
        + "maxLayer:" + MaxLayer + ","
        + "maxTriggerTimes:" + MaxTriggerTimes + ","
        + "refreshMode:" + RefreshMode + ","
        + "triggerMode:" + TriggerMode + ","
        + "triggerInterval:" + TriggerInterval + ","
        + "removeMode:" + RemoveMode + ","
        + "removeEvent:" + RemoveEvent + ","
        + "treeName:" + TreeName + ","
        + "}";
    }
}

}
