
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class CommonConstantDesc : Luban.BeanBase
{
    public CommonConstantDesc(ByteBuf _buf) 
    {
        GoldCoinID = _buf.ReadInt();
    }

    public static CommonConstantDesc DeserializeCommonConstantDesc(ByteBuf _buf)
    {
        return new CommonConstantDesc(_buf);
    }

    /// <summary>
    /// 金币id
    /// </summary>
    public readonly int GoldCoinID;
   
    public const int __ID__ = 692426240;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
    }

    public override string ToString()
    {
        return "{ "
        + "GoldCoinID:" + GoldCoinID + ","
        + "}";
    }
}

}
