
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum EBuffRefreshMode
    {
        None = 0,
        AddLayer = 1,
        RefreshDuration = 2,
        AddDuration = 4,
    }

} 

