
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum EBuffTriggerMethod
    {
        None = 0,
        OnEvent = 1,
        Repeat = 2,
        OnAction = 4,
    }

} 

