
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class EffectDesc : Luban.BeanBase
{
    public EffectDesc(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Level = _buf.ReadInt();
        Index = _buf.ReadInt();
        Name = _buf.ReadString();
        Trigger = Battle.EffectTriggerDesc.DeserializeEffectTriggerDesc(_buf);
        Effect = Battle.Effect.DeserializeEffect(_buf);
    }

    public static EffectDesc DeserializeEffectDesc(ByteBuf _buf)
    {
        return new EffectDesc(_buf);
    }

    /// <summary>
    /// 技能ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 等级
    /// </summary>
    public readonly int Level;
    public readonly int Index;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    public readonly Battle.EffectTriggerDesc Trigger;
    public readonly Battle.Effect Effect;
   
    public const int __ID__ = -586164254;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        Trigger?.ResolveRef(tables);
        Effect?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "level:" + Level + ","
        + "index:" + Index + ","
        + "name:" + Name + ","
        + "trigger:" + Trigger + ","
        + "effect:" + Effect + ","
        + "}";
    }
}

}
