
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig
{ 
    public enum ESkillType
    {
        NormalAttack = 0,
        CounterAttack = 1,
        Proactive = 2,
        Passive = 3,
        Buff = 4,
    }

} 

