
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class FetterDesc : Luban.BeanBase
{
    public FetterDesc(ByteBuf _buf) 
    {
        Level = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);RateAdds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); RateAdds.Add(_e0);}}
    }

    public static FetterDesc DeserializeFetterDesc(ByteBuf _buf)
    {
        return new FetterDesc(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Level;
    public readonly System.Collections.Generic.List<int> RateAdds;
   
    public const int __ID__ = 137382205;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "level:" + Level + ","
        + "rateAdds:" + Luban.StringUtil.CollectionToString(RateAdds) + ","
        + "}";
    }
}

}
