
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class HeroDesc : Luban.BeanBase
{
    public HeroDesc(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        Icon = _buf.ReadString();
        ShowId = _buf.ReadInt();
        Radius = _buf.ReadFloat();
        Height = _buf.ReadFloat();
        ShapeType = (GameLogic.Battle.ERoleShape)_buf.ReadInt();
        AiName = _buf.ReadString();
        SkillId = _buf.ReadInt();
        PassiveBuffId = _buf.ReadInt();
        Hp = _buf.ReadInt();
        Attack = _buf.ReadInt();
    }

    public static HeroDesc DeserializeHeroDesc(ByteBuf _buf)
    {
        return new HeroDesc(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 说明
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 头像
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 表现id
    /// </summary>
    public readonly int ShowId;
    /// <summary>
    /// 半径
    /// </summary>
    public readonly float Radius;
    /// <summary>
    /// 高度
    /// </summary>
    public readonly float Height;
    /// <summary>
    /// 形状
    /// </summary>
    public readonly GameLogic.Battle.ERoleShape ShapeType;
    public readonly string AiName;
    /// <summary>
    /// 攻击技能id
    /// </summary>
    public readonly int SkillId;
    /// <summary>
    /// 被动技能buff
    /// </summary>
    public readonly int PassiveBuffId;
    public readonly int Hp;
    public readonly int Attack;
   
    public const int __ID__ = -554755637;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "icon:" + Icon + ","
        + "showId:" + ShowId + ","
        + "radius:" + Radius + ","
        + "height:" + Height + ","
        + "shapeType:" + ShapeType + ","
        + "aiName:" + AiName + ","
        + "skillId:" + SkillId + ","
        + "passiveBuffId:" + PassiveBuffId + ","
        + "hp:" + Hp + ","
        + "attack:" + Attack + ","
        + "}";
    }
}

}
