
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.item
{
public partial class TbItem
{
    public static TbItem Instance => ConfigSystem.Instance.Tables.TbItem;
    private readonly System.Collections.Generic.Dictionary<int, ItemDesc> _dataMap;
    private readonly System.Collections.Generic.List<ItemDesc> _dataList;
    
    public TbItem(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, ItemDesc>();
        _dataList = new System.Collections.Generic.List<ItemDesc>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            ItemDesc _v;
            _v = ItemDesc.DeserializeItemDesc(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ItemDesc> DataMap => _dataMap;
    public System.Collections.Generic.List<ItemDesc> DataList => _dataList;

    public ItemDesc GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ItemDesc Get(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ItemDesc this[int key] => _dataMap.TryGetValue(key, out var v) ? v : null;

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

    

}

}
