
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class MainlandActorShow : Luban.BeanBase
{
    public MainlandActorShow(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Description = _buf.ReadString();
        Model = _buf.ReadString();
    }

    public static MainlandActorShow DeserializeMainlandActorShow(ByteBuf _buf)
    {
        return new MainlandActorShow(_buf);
    }

    /// <summary>
    /// 表现id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 介绍
    /// </summary>
    public readonly string Description;
    /// <summary>
    /// 模型
    /// </summary>
    public readonly string Model;
   
    public const int __ID__ = 567446446;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "description:" + Description + ","
        + "model:" + Model + ","
        + "}";
    }
}

}
