
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class MainlandDesc : Luban.BeanBase
{
    public MainlandDesc(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Seq = _buf.ReadInt();
        Chapter = _buf.ReadInt();
        Title = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);MonsterIdGroups = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); MonsterIdGroups.Add(_e0);}}
        Gold = _buf.ReadInt();
    }

    public static MainlandDesc DeserializeMainlandDesc(ByteBuf _buf)
    {
        return new MainlandDesc(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 关卡编号
    /// </summary>
    public readonly int Seq;
    /// <summary>
    /// 章节
    /// </summary>
    public readonly int Chapter;
    /// <summary>
    /// 标题
    /// </summary>
    public readonly string Title;
    /// <summary>
    /// 怪物组
    /// </summary>
    public readonly System.Collections.Generic.List<int> MonsterIdGroups;
    /// <summary>
    /// 奖励金币
    /// </summary>
    public readonly int Gold;
   
    public const int __ID__ = 1110419445;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "seq:" + Seq + ","
        + "chapter:" + Chapter + ","
        + "title:" + Title + ","
        + "monsterIdGroups:" + Luban.StringUtil.CollectionToString(MonsterIdGroups) + ","
        + "gold:" + Gold + ","
        + "}";
    }
}

}
