
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Mainland
{
public sealed partial class MonsterGroupOne : Luban.BeanBase
{
    public MonsterGroupOne(ByteBuf _buf) 
    {
        MonsterId = _buf.ReadInt();
        FeatureId = _buf.ReadInt();
    }

    public static MonsterGroupOne DeserializeMonsterGroupOne(ByteBuf _buf)
    {
        return new Mainland.MonsterGroupOne(_buf);
    }

    public readonly int MonsterId;
    public readonly int FeatureId;
   
    public const int __ID__ = -1890880873;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "monsterId:" + MonsterId + ","
        + "featureId:" + FeatureId + ","
        + "}";
    }
}

}
