
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class MonsterFeatureDesc : Luban.BeanBase
{
    public MonsterFeatureDesc(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Hp = _buf.ReadInt();
        Attack = _buf.ReadInt();
        Def = _buf.ReadInt();
        MagicAttack = _buf.ReadInt();
        MagicDef = _buf.ReadInt();
        Crit = _buf.ReadInt();
        CriticalDamageRate = _buf.ReadInt();
    }

    public static MonsterFeatureDesc DeserializeMonsterFeatureDesc(ByteBuf _buf)
    {
        return new MonsterFeatureDesc(_buf);
    }

    /// <summary>
    /// 特征id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 生命
    /// </summary>
    public readonly int Hp;
    /// <summary>
    /// 攻击力
    /// </summary>
    public readonly int Attack;
    /// <summary>
    /// 防御
    /// </summary>
    public readonly int Def;
    /// <summary>
    /// 法强
    /// </summary>
    public readonly int MagicAttack;
    /// <summary>
    /// 魔抗
    /// </summary>
    public readonly int MagicDef;
    /// <summary>
    /// 暴击率千分比
    /// </summary>
    public readonly int Crit;
    /// <summary>
    /// 暴击伤害率千分比
    /// </summary>
    public readonly int CriticalDamageRate;
   
    public const int __ID__ = -1879240051;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "hp:" + Hp + ","
        + "attack:" + Attack + ","
        + "def:" + Def + ","
        + "magicAttack:" + MagicAttack + ","
        + "magicDef:" + MagicDef + ","
        + "crit:" + Crit + ","
        + "criticalDamageRate:" + CriticalDamageRate + ","
        + "}";
    }
}

}
