
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class MonsterGroupDesc : Luban.BeanBase
{
    public MonsterGroupDesc(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);MonsterIds = new System.Collections.Generic.List<Mainland.MonsterGroupOne>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Mainland.MonsterGroupOne _e0;  _e0 = Mainland.MonsterGroupOne.DeserializeMonsterGroupOne(_buf); MonsterIds.Add(_e0);}}
    }

    public static MonsterGroupDesc DeserializeMonsterGroupDesc(ByteBuf _buf)
    {
        return new MonsterGroupDesc(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    public readonly System.Collections.Generic.List<Mainland.MonsterGroupOne> MonsterIds;
   
    public const int __ID__ = 597648150;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        foreach (var _e in MonsterIds) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "monsterIds:" + Luban.StringUtil.CollectionToString(MonsterIds) + ","
        + "}";
    }
}

}
