
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    #region The Tables

    private TbSpell m_TbSpell;
    public TbSpell TbSpell 
    {
        get
        {
            if (m_TbSpell == null)
            {
                m_TbSpell = new TbSpell(defaultLoader("tbspell"));
                m_TbSpell.ResolveRef(this);
            }
            return m_TbSpell;
        }
        set
        {
            m_TbSpell = value;
            m_TbSpell.ResolveRef(this);
        }
    }
    private TbEffect m_TbEffect;
    public TbEffect TbEffect 
    {
        get
        {
            if (m_TbEffect == null)
            {
                m_TbEffect = new TbEffect(defaultLoader("tbeffect"));
                m_TbEffect.ResolveRef(this);
            }
            return m_TbEffect;
        }
        set
        {
            m_TbEffect = value;
            m_TbEffect.ResolveRef(this);
        }
    }
    private TbBuff m_TbBuff;
    public TbBuff TbBuff 
    {
        get
        {
            if (m_TbBuff == null)
            {
                m_TbBuff = new TbBuff(defaultLoader("tbbuff"));
                m_TbBuff.ResolveRef(this);
            }
            return m_TbBuff;
        }
        set
        {
            m_TbBuff = value;
            m_TbBuff.ResolveRef(this);
        }
    }

    #endregion

    System.Func<string, ByteBuf> defaultLoader;

    public Tables(System.Func<string, ByteBuf> loader)
    {
        SetDefaultLoader(loader);
        Init();
    }
    
    public void SetDefaultLoader(System.Func<string, ByteBuf> loader)
    {
        defaultLoader = null;
        defaultLoader = loader;
    }

    //public partial void Init();

    public void Init(){}
}

}
