
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class TbBuff
{
    public static TbBuff Instance => ConfigSystem.Instance.Tables.TbBuff;
    private readonly System.Collections.Generic.Dictionary<int, BuffDesc> _dataMap;
    private readonly System.Collections.Generic.List<BuffDesc> _dataList;
    
    public TbBuff(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, BuffDesc>();
        _dataList = new System.Collections.Generic.List<BuffDesc>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            BuffDesc _v;
            _v = BuffDesc.DeserializeBuffDesc(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, BuffDesc> DataMap => _dataMap;
    public System.Collections.Generic.List<BuffDesc> DataList => _dataList;

    public BuffDesc GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public BuffDesc Get(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public BuffDesc this[int key] => _dataMap.TryGetValue(key, out var v) ? v : null;

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

    

}

}
