
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class TbCardDesc
{
    public static TbCardDesc Instance => ConfigSystem.Instance.Tables.TbCardDesc;
    private readonly System.Collections.Generic.Dictionary<int, CardDesc> _dataMap;
    private readonly System.Collections.Generic.List<CardDesc> _dataList;
    
    public TbCardDesc(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, CardDesc>();
        _dataList = new System.Collections.Generic.List<CardDesc>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            CardDesc _v;
            _v = CardDesc.DeserializeCardDesc(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, CardDesc> DataMap => _dataMap;
    public System.Collections.Generic.List<CardDesc> DataList => _dataList;

    public CardDesc GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public CardDesc Get(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public CardDesc this[int key] => _dataMap.TryGetValue(key, out var v) ? v : null;

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

    

}

}
