
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class TbCommonConstant
{
    public static TbCommonConstant Instance => ConfigSystem.Instance.Tables.TbCommonConstant;
    private readonly System.Collections.Generic.List<CommonConstantDesc> _dataList;


    public TbCommonConstant(ByteBuf _buf)
    {
        _dataList = new System.Collections.Generic.List<CommonConstantDesc>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            CommonConstantDesc _v;
            _v = CommonConstantDesc.DeserializeCommonConstantDesc(_buf);
            _dataList.Add(_v);
        }
    }

    public System.Collections.Generic.List<CommonConstantDesc> DataList => _dataList;

    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}
