
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class TbFetterDesc
{
    public static TbFetterDesc Instance => ConfigSystem.Instance.Tables.TbFetterDesc;
    private readonly System.Collections.Generic.Dictionary<int, FetterDesc> _dataMap;
    private readonly System.Collections.Generic.List<FetterDesc> _dataList;
    
    public TbFetterDesc(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, FetterDesc>();
        _dataList = new System.Collections.Generic.List<FetterDesc>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            FetterDesc _v;
            _v = FetterDesc.DeserializeFetterDesc(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Level, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, FetterDesc> DataMap => _dataMap;
    public System.Collections.Generic.List<FetterDesc> DataList => _dataList;

    public FetterDesc GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public FetterDesc Get(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public FetterDesc this[int key] => _dataMap.TryGetValue(key, out var v) ? v : null;

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

    

}

}
