
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class TbHeroDesc
{
    public static TbHeroDesc Instance => ConfigSystem.Instance.Tables.TbHeroDesc;
    private readonly System.Collections.Generic.Dictionary<int, HeroDesc> _dataMap;
    private readonly System.Collections.Generic.List<HeroDesc> _dataList;
    
    public TbHeroDesc(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, HeroDesc>();
        _dataList = new System.Collections.Generic.List<HeroDesc>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            HeroDesc _v;
            _v = HeroDesc.DeserializeHeroDesc(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, HeroDesc> DataMap => _dataMap;
    public System.Collections.Generic.List<HeroDesc> DataList => _dataList;

    public HeroDesc GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public HeroDesc Get(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public HeroDesc this[int key] => _dataMap.TryGetValue(key, out var v) ? v : null;

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

    

}

}
