
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class TbMainlandActorShow
{
    public static TbMainlandActorShow Instance => ConfigSystem.Instance.Tables.TbMainlandActorShow;
    private readonly System.Collections.Generic.Dictionary<int, MainlandActorShow> _dataMap;
    private readonly System.Collections.Generic.List<MainlandActorShow> _dataList;
    
    public TbMainlandActorShow(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, MainlandActorShow>();
        _dataList = new System.Collections.Generic.List<MainlandActorShow>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            MainlandActorShow _v;
            _v = MainlandActorShow.DeserializeMainlandActorShow(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, MainlandActorShow> DataMap => _dataMap;
    public System.Collections.Generic.List<MainlandActorShow> DataList => _dataList;

    public MainlandActorShow GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public MainlandActorShow Get(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public MainlandActorShow this[int key] => _dataMap.TryGetValue(key, out var v) ? v : null;

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

    

}

}
