
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class TbMainlandDesc
{
    public static TbMainlandDesc Instance => ConfigSystem.Instance.Tables.TbMainlandDesc;
    private readonly System.Collections.Generic.Dictionary<int, MainlandDesc> _dataMap;
    private readonly System.Collections.Generic.List<MainlandDesc> _dataList;
    
    public TbMainlandDesc(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, MainlandDesc>();
        _dataList = new System.Collections.Generic.List<MainlandDesc>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            MainlandDesc _v;
            _v = MainlandDesc.DeserializeMainlandDesc(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, MainlandDesc> DataMap => _dataMap;
    public System.Collections.Generic.List<MainlandDesc> DataList => _dataList;

    public MainlandDesc GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public MainlandDesc Get(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public MainlandDesc this[int key] => _dataMap.TryGetValue(key, out var v) ? v : null;

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

    

}

}
