
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class TbMonsterFeatureDesc
{
    public static TbMonsterFeatureDesc Instance => ConfigSystem.Instance.Tables.TbMonsterFeatureDesc;
    private readonly System.Collections.Generic.Dictionary<int, MonsterFeatureDesc> _dataMap;
    private readonly System.Collections.Generic.List<MonsterFeatureDesc> _dataList;
    
    public TbMonsterFeatureDesc(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, MonsterFeatureDesc>();
        _dataList = new System.Collections.Generic.List<MonsterFeatureDesc>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            MonsterFeatureDesc _v;
            _v = MonsterFeatureDesc.DeserializeMonsterFeatureDesc(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, MonsterFeatureDesc> DataMap => _dataMap;
    public System.Collections.Generic.List<MonsterFeatureDesc> DataList => _dataList;

    public MonsterFeatureDesc GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public MonsterFeatureDesc Get(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public MonsterFeatureDesc this[int key] => _dataMap.TryGetValue(key, out var v) ? v : null;

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

    

}

}
