
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class TbMonsterDesc
{
    public static TbMonsterDesc Instance => ConfigSystem.Instance.Tables.TbMonsterDesc;
    private readonly System.Collections.Generic.Dictionary<int, MonsterDesc> _dataMap;
    private readonly System.Collections.Generic.List<MonsterDesc> _dataList;
    
    public TbMonsterDesc(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, MonsterDesc>();
        _dataList = new System.Collections.Generic.List<MonsterDesc>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            MonsterDesc _v;
            _v = MonsterDesc.DeserializeMonsterDesc(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, MonsterDesc> DataMap => _dataMap;
    public System.Collections.Generic.List<MonsterDesc> DataList => _dataList;

    public MonsterDesc GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public MonsterDesc Get(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public MonsterDesc this[int key] => _dataMap.TryGetValue(key, out var v) ? v : null;

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

    

}

}
