
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class TbSpell
{
    public static TbSpell Instance => ConfigSystem.Instance.Tables.TbSpell;
    private readonly System.Collections.Generic.Dictionary<int, SpellDesc> _dataMap;
    private readonly System.Collections.Generic.List<SpellDesc> _dataList;
    
    public TbSpell(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, SpellDesc>();
        _dataList = new System.Collections.Generic.List<SpellDesc>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            SpellDesc _v;
            _v = SpellDesc.DeserializeSpellDesc(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, SpellDesc> DataMap => _dataMap;
    public System.Collections.Generic.List<SpellDesc> DataList => _dataList;

    public SpellDesc GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public SpellDesc Get(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public SpellDesc this[int key] => _dataMap.TryGetValue(key, out var v) ? v : null;

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

    

}

}
